Make sure ZUUL_UUID is present when syncing doc
When triggering a job manually, we might not set ZUUL_UUID which would
cause rsync to delete everything on the publisher AND on
https://doc.wikimedia.org/

Abort publish process whenever ZUUL_UUID is not set.

Change-Id: If2c0840d54a400e9999efa20128dce89ff3b9220

diff --git a/jjb/doc.yaml b/jjb/doc.yaml
--- a/jjb/doc.yaml
+++ b/jjb/doc.yaml
@@ -18,6 +18,11 @@
     builders:
      # rsync {docsrc} folder to integration-publisher.eqiad.wmflabs
      - shell: |
+         if [ -z $ZUUL_UUID ]; then
+            echo "Parameter \$ZUUL_UUID is missing!"
+            echo "Can not rsync the documentation, aborting."
+            exit 1
+         fi
          rsync --recursive "{docsrc}/" "rsync://10.68.16.255/doc/$ZUUL_UUID"
      # rsync folder to doc.wikimedia.org
      - trigger-builds:
@@ -51,6 +56,11 @@
          if [ "$WMF_CI_DOC_DEST" == "" ]; then
              echo "WMF_CI_DOC_DEST parameter is empty. Aborting"
              exit 1
+         fi
+         if [ -z $ZUUL_UUID ]; then
+            echo "Parameter \$ZUUL_UUID is missing!"
+            echo "Can not rsync the documentation, aborting."
+            exit 1
          fi
          rsync --recursive --delete-after "rsync://10.68.16.255/doc/$ZUUL_UUID"/ "/srv/org/wikimedia/doc/$WMF_CI_DOC_DEST"
      - shell: |
