Support MediaWiki core under HHVM
Experimental replacement of mediawiki-phpunit with two new jobs:

    mediawiki-phpunit-hhvm  (hhvm from Trusty)
    mediawiki-phpunit-zend  (PHP 5.3 from Precise)

Depends on puppet change https://gerrit.wikimedia.org/r/178806/ which is
already applied on the contint slaves.

Add an assertion macro to make sure we use the proper PHP flavor. Pass
it either 'hhvm' or 'zend' and it will parse 'php --version', aborting
on mismatch.

Add a macro to delete '*.hhbc' files. They are bytecodes compiler cache
files generated by hhvm.  Set via the HHVM_REPO_CENTRAL_PATH env
variable.

Convert the 'mediawiki-phpunit' job template to vary by a new variable
'phpflavor'. The variable is used to select a proper node using a crazy
label expression. CI slaves labels have been adjusted already with
either 'phpflavor-hhvm' or 'phpflavor-zend'.

Add the new jobs to the experimental pipeline of mediawiki/core so
people can manually trigger them from Gerrit by commenting:
'check experimental'.

Keep the old 'mediawiki-phpunit' job around since it is still triggered.

Do not run the hhvm job on REL1_23/REL1_24 branch, leaving it open for
the future REL1_25 branch though.

TODO:
* migrate the testextension jobs
* migrate the qunit jobs
* Fix hhvm test ApiFormatWddx (T75531). That is a bug upstrem which
  would be fixed with a new hhvm version scheduled to be deployed next
  week (-wm6).

Bug: T75521
Change-Id: I924a42d2001edafa5ab00623b342afd87cfa5334

diff --git a/jjb/macro.yaml b/jjb/macro.yaml
--- a/jjb/macro.yaml
+++ b/jjb/macro.yaml
@@ -225,6 +225,45 @@
              exit 1
          fi
 
+# Assert 'php' is phpflavor
+#
+# Parameter:
+# * phpflavor: 'hhvm' or 'zend'
+#
+- builder:
+    name: assert-phpflavor
+    builders:
+        - shell: |
+            #!/bin/bash -e -u
+            PHP_VERSION=`php --version`
+
+            case "{phpflavor}" in
+                ( 'hhvm' )
+                    MATCHER='^HipHop'
+                ;;
+                ( 'zend' )
+                    MATCHER='^Zend Engine'
+                ;;
+                ( * )
+                    echo "Invalid phpflavor '{phpflavor}' for JJB macro 'assert-phpflavor'"
+                    echo "Must be either 'hhvm' or 'zend'"
+                    exit 1
+                ;;
+            esac
+
+            if ( echo "$PHP_VERSION" | egrep "$MATCHER" > /dev/null ); then
+                echo -e "php is {phpflavor}:\n\n$PHP_VERSION\n"
+            else
+                echo -e "Assertion error: php is not {phpflavor}:\n\n$PHP_VERSION\n"
+                exit 1
+            fi
+
+- builder:
+    name: 'hhvm-clear-hhbc'
+    builders:
+        - shell: |
+            rm -f *.hhbc
+
 # Assert node version matches a basic regular expressions
 #
 # Parameter:
