Add macro for asserting DOC_SUBPATH is set
The builder assert-env-doc_subpath let us ensure DOC_SUBPATH is
available. It is set by Zuul and used when generating documentation:

https://www.mediawiki.org/wiki/CI/Documentation_generation

Change-Id: Ibceb6fc700848283acc96a80b4adeae367a85cc0

diff --git a/jjb/macro.yaml b/jjb/macro.yaml
--- a/jjb/macro.yaml
+++ b/jjb/macro.yaml
@@ -216,6 +216,15 @@
         npm install
         npm test
 
+- builder:
+    name: assert-env-doc_subpath
+    builders:
+     - shell: |
+         if [ -z $DOC_SUBPATH ]; then
+             echo "\$DOC_SUBPATH is missing. Can not publish."
+             exit 1
+         fi
+
 # Assert node version matches a basic regular expressions
 #
 # Parameter:
