Try MediaWiki code coverage on Jessie/php7
Create mediawiki-core-code-coverage-php7

Change-Id: I1d8ecdc51428995430b53207d1651bf9187d8bee

diff --git a/jjb/mediawiki.yaml b/jjb/mediawiki.yaml
--- a/jjb/mediawiki.yaml
+++ b/jjb/mediawiki.yaml
@@ -438,6 +438,93 @@
      - ansicolor
      - timestamps
 
+- job:
+    name: 'mediawiki-core-code-coverage-php7'
+    node: contintLabsSlave && DebianJessie
+    # Set env variables needed by zuul-cloner since job is not triggered by
+    # Zuul but is timed using Jenkins own scheduler.
+    parameters:
+     - string:
+         name: 'PHP_BIN'
+         default: 'php7.0'
+     - string:
+         name: 'ZUUL_UUID'
+         default: 'mwcore-cover_not-very-random'
+     - string:
+         name: 'ZUUL_BRANCH'
+         default: 'master'
+     - string:
+         name: 'ZUUL_REF'
+         default: 'master'
+     - string:
+         name: 'ZUUL_CHANGE'
+         default: 'timed_build'
+     - string:
+         name: 'ZUUL_PATCHSET'
+         default: 'timed_build'
+     - string:
+         name: 'ZUUL_PIPELINE'
+         default: 'timed_build'
+     - string:
+         name: 'ZUUL_PROJECT'
+         default: 'mediawiki/core'
+     - string:
+         name: 'ZUUL_URL'
+         default: 'https://gerrit.wikimedia.org/r/p'
+    builders:
+     - zuul-cloner:
+         projects: >
+             mediawiki/core
+             mediawiki/vendor
+     - mw-install-sqlite
+     - mw-apply-settings
+     - mw-fetch-composer-dev
+     # FIXME should use the mw-phpunit.sh wrapper
+     - shell: |
+        . "/srv/deployment/integration/slave-scripts/bin/mw-set-env.sh"
+
+        mkdir -p log
+        rm -f log/clover.xml log/clover.bz2
+
+        # Since clover file are huge, compress them before archiving
+        # We need to keep the original though for the cloverphp plugin
+        function compress_clover_log() {
+            if [ -s "log/clover.xml" ]; then
+                echo "Compressing log/clover.xml with bz2..."
+                bzip2 --verbose --best --keep log/clover.xml
+                echo "Compression completed."
+            fi
+        }
+        trap compress_clover_log EXIT
+
+        rm -fR "$WORKSPACE/cover"
+        mkdir -p "$WORKSPACE/cover"
+
+        nice -n 19 php $MW_INSTALL_PATH/tests/phpunit/phpunit.php \
+            --exclude-group Dump,Broken,ParserFuzz,Stub \
+            --coverage-clover log/clover.xml \
+            --coverage-html "$WORKSPACE/cover" \
+            || :
+
+        # PHP segfault (bug 43972) so ignore any error with '|| :' or the
+        # Jenkins plugin will never generate the coverage report for us
+        # https://issues.jenkins-ci.org/browse/JENKINS-21046
+#     - cover-publish:
+#         src: 'cover'
+#         dest: 'mediawiki-core/$ZUUL_BRANCH/php'
+    publishers:
+     - archive:
+         artifacts: 'log/clover.xml.bz2'
+     - cloverphp:
+         xml-location: 'log/clover.xml'
+     - mw-teardown
+#     - beta-irc  # Spam #wikimedia-releng on failure
+    triggers:
+     - timed: '0 3,15 * * *'
+    wrappers:
+     - ansicolor
+     - timestamps
+
 # Special job to run MW-CS against MediaWiki core.
 # Can't run it through composer because it'll timeout.
 - job:
