Publish coverage for Wikibase on post merge
Depends-On: I2c0b3ce53c64ffef7ed41de696240757744931f4
Change-Id: I969e5846b6a6983d639adbb42e614e876618e86d

diff --git a/jjb/mediawiki-extensions.yaml b/jjb/mediawiki-extensions.yaml
--- a/jjb/mediawiki-extensions.yaml
+++ b/jjb/mediawiki-extensions.yaml
@@ -644,3 +644,59 @@
          fail: true
      - ansicolor
      - timestamps
+
+- job:
+    name: 'mwext-phpunit-coverage-publish-Wikibase'
+    node: ci-jessie-wikimedia
+    builders:
+     - prepare-mwext-coverage
+     - shell: |
+        . "/srv/deployment/integration/slave-scripts/bin/mw-set-env.sh"
+
+        mkdir -p log
+        rm -f log/clover.xml log/clover.bz2
+
+        rm -fR "$WORKSPACE/cover"
+        mkdir -p "$WORKSPACE/cover"
+
+        nice -n 19 \
+            php7.0 -d zend_extension=xdebug.so \
+                $MW_INSTALL_PATH/tests/phpunit/phpunit.php \
+                    --testsuite WikibaseTests \
+                    --coverage-clover log/clover.xml \
+                    --coverage-html "$WORKSPACE/cover" \
+                    --configuration "$MW_INSTALL_PATH/extensions/Wikibase/phpunit.xml.dist" \
+            || :
+        # Above: Use "|| :" to ignore any non-zero exist status
+        # We want to publish code coverage even in case one of there
+        # being PHPUnit test failures. Normal test failures are not
+        # fatal and PHPUnit will stil generate console output, clover
+        # reports and and html reports. However don't blindly
+        # make the job pass either because if we do, then cover-publish
+        # will end up syncing an empty directory, which deletes the
+        # coverage report from doc.wikimedia.org. In case of "real" failure,
+        # let the job fail and don't publish a new report. "real" failures
+        # can be a PHP Fatal error, of a segfault, for example.
+        test -f cover/index.html
+
+        if [ -s "log/clover.xml" ]; then
+            cp log/clover.xml "$WORKSPACE/cover/clover.xml"
+        fi
+
+     - cover-extensions-publish:
+         src: 'cover'
+         # Should be equivalent to $EXT_NAME
+         dest: '$DOC_BASENAME'
+    publishers:
+     - archive:
+         artifacts: 'log/*'
+     - mw-teardown
+     - beta-irc  # Spam #wikimedia-releng on failure
+    triggers:
+     - zuul
+    wrappers:
+     - timeout:
+         timeout: 20
+         fail: true
+     - ansicolor
+     - timestamps
