Migrate mw doxygen to zuul-cloner and Trusty
Job is no more bound to gallium by using the push-doc macro see doc
https://www.mediawiki.org/wiki/Continuous_integration/Documentation_generation

Ubuntu Trusty has doxygen 1.8.6 (bug 46771)
Migrate to Zuul cloner (bug 72837)
TARGET_BASEDIR is recognized by mwcore-docgen.sh slave script and used
to override the destination.

Use DOC_SUBPATH generated by Zuul which is the version extracted from
the branch or tag refspec. mwcore-docgen no more carry that logic since
https://gerrit.wikimedia.org/r/#/c/173295/

Bug: 46771
Bug: 72837
Change-Id: I1fd6d23917c2098dbdad37d9e718335616207f68

diff --git a/jjb/mediawiki.yaml b/jjb/mediawiki.yaml
--- a/jjb/mediawiki.yaml
+++ b/jjb/mediawiki.yaml
@@ -93,21 +93,27 @@
 
 - job:
     name: 'mediawiki-core-doxygen-publish'
-    node: gallium
-    defaults: use-zuul
+    node: contintLabsSlave && UbuntuTrusty
     concurrent: false
-    scm:
-     - git-mwcore
-     - git:
-        url: '/srv/ssd/gerrit/mediawiki/vendor'
-        branches:
-          - master
-        wipe-workspace: false
-        basedir: vendor
     triggers:
      - zuul
     builders:
-     - shell: "/srv/deployment/integration/slave-scripts/tools/mwcore-docgen.sh"
+     - shell: |
+         if [ -z $DOC_SUBPATH ]; then
+             echo "\$DOC_SUBPATH is missing. Can not publish."
+             exit 1
+         fi
+     - zuul-cloner:
+         projects: >
+             mediawiki/core
+             mediawiki/vendor
+     - shell: |
+         rm -fR build/doc
+         mkdir -p build/doc
+         TARGET_BASEDIR="$WORKSPACE/build/doc" /srv/deployment/integration/slave-scripts/tools/mwcore-docgen.sh
+     - push-doc:
+         docsrc: 'build/doc'
+         docdest: 'mediawiki-core/$DOC_SUBPATH'
 
 - job-template:
     name: '{name}-whitespaces'
