Add a test for unlucky .pp files that break puppet runs.
Due to a bug identified in TT119042, any manifest
in the puppet/modules/manifests/role directory will
cause puppet to throw up.  Files in subdirs are fine.

Bug: T144774
Change-Id: I7ac8865d03a21493a35e1dc9d7b658e230dd083d

diff --git a/jjb/operations-puppet.yaml b/jjb/operations-puppet.yaml
--- a/jjb/operations-puppet.yaml
+++ b/jjb/operations-puppet.yaml
@@ -11,6 +11,31 @@
     builders:
      - shell: "/srv/deployment/integration/slave-scripts/bin/puppet-test-runner.sh"
 
+# Detect problematic manifests that break puppet runs as per T119042
+- operations-puppet-path-check:
+    name: 'operations-puppet-path-check'
+
+    node: contintLabsSlave
+    defaults: use-remote-zuul-shallow-clone
+    concurrent: true
+
+    triggers:
+     - zuul
+
+    builders:
+     - shell: |
+        #!/bin/bash -e
+        echo "Checking for invalid manifest paths."
+
+        BAD=0
+        shopt -s nullglob
+        for f in modules/role/manifests/*.pp; do
+            echo "Invalid manifest path found: ${f}.  See T119042 for explanation."
+            BAD=1
+        done
+
+        exit $BAD
+
 # Documentation for our puppet repository
 - job-template:
     name: 'operations-puppet-doc'
@@ -57,6 +82,7 @@
     jobs:
      - '{name}-puppetlint-strict'
      - '{name}-typos'
+     - operations-puppet-path-check
      - '{name}-tox-jessie'
      - operations-puppet-test
      - operations-puppet-doc
