operations-puppet-typos now handle missing /typos
9ac8d27f removed the /typos file which is used by the Jenkins job
operations-puppet-typos.  grep would exit 2 which was handled as if no
typo occurred.

Change to a switch/case statemenent for easier handling of grep exit
code.

Bug: T100989
Change-Id: Ida1f03359fe85c705ba6d8977a8be3e30d6f78f5

diff --git a/jjb/operations-puppet.yaml b/jjb/operations-puppet.yaml
--- a/jjb/operations-puppet.yaml
+++ b/jjb/operations-puppet.yaml
@@ -65,9 +65,23 @@
      - shell: |
         #!/bin/bash -e
 
-        echo "Looking for usage of 'pmpta' instead of 'pmtpa'..."
-        (fgrep -R --file=typos --exclude=typos *) && HAS_TYPO=1 || HAS_TYPO=0
-        exit $HAS_TYPO
+        echo "Looking potential typos from '/typos' file"
+        (fgrep -R --file=typos --exclude=typos *)
+        ERR="$?"
+        case $ERR in
+            "0")
+                echo "Typos found!"
+                exit 1
+                ;;
+            "1")
+                echo "No typos found!"
+                exit 0
+                ;;
+            *)
+                echo "Some error occured."
+                exit $ERR
+                ;;
+        esac
 
 - project:
     name: 'operations-puppet'
