Publish oojs code coverage to integration.wikimedia.org
Requires I5dbd155ac9 in oojs/core.

Bug: T93558
Bug: T87490
Change-Id: I9b20a368d3941e4fddf26391e51f47d567c457f3

diff --git a/jjb/publish.yaml b/jjb/publish.yaml
--- a/jjb/publish.yaml
+++ b/jjb/publish.yaml
@@ -2,8 +2,6 @@
 # another job (executing on gallium) can pull in the files and publish them
 # on https://doc.wikimedia.org/.
 #
-# Uses $ZUUL_UUID as a unique identifier.
-#
 # Parameters:
 #
 # docsrc: Directory holding documentation files relative to workspace (without trailing slash)
@@ -14,7 +12,7 @@
     docsrc: '{docsrc}'
     docdest: '{docdest}'
     builders:
-     # rsync {docsrc} folder to integration-publisher.eqiad.wmflabs
+     # rsync folder to integration-publisher.eqiad.wmflabs
      - shell: |
          if [ -z $ZUUL_UUID ]; then
             echo "Error: ZUUL_UUID must be set, aborting."
@@ -30,6 +28,37 @@
          predefined-parameters: |
            WMF_CI_PUB_DOCROOT=org/wikimedia/doc
            WMF_CI_PUB_DEST={docdest}
+
+# Sync files from a Jenkins slave in labs to a central rsync server from which
+# another job (executing on gallium) can pull in the files and publish them
+# on https://integration.wikimedia.org/cover/.
+#
+# Parameters:
+#
+# src: Directory holding documentation files relative to workspace (without trailing slash)
+# dest: Directory under integration.wikimedia.org/cover/
+#
+- builder:
+    name: cover-publish
+    docsrc: '{docsrc}'
+    docdest: '{docdest}'
+    builders:
+     # rsync folder to integration-publisher.eqiad.wmflabs
+     - shell: |
+         if [ -z $ZUUL_UUID ]; then
+            echo "Error: ZUUL_UUID must be set, aborting."
+            exit 1
+         fi
+         rsync --recursive "{src}/" "rsync://10.68.16.255/doc/$ZUUL_UUID"
+         echo
+         echo "Publishing to https://integration.wikimedia.org/cover/{dest}/"
+     - trigger-builds:
+       - project: publish-on-gallium
+         block: true
+         current-parameters: true  # Pass Zuul parameters
+         predefined-parameters: |
+           WMF_CI_PUB_DOCROOT=org/wikimedia/doc
+           WMF_CI_PUB_DEST=cover/{dest}
 
 # rsync a directory from integration-publisher.eqiad.wmflabs to a website on gallium.
 #
