Use DOC_SUBPATH instead of ZUUL_BRANCH for misc publish jobs
Change-Id: I8b4bcb5eb0cd2ae05a1f0f3458ba6d0a76f07ef9

diff --git a/jjb/publish.yaml b/jjb/publish.yaml
--- a/jjb/publish.yaml
+++ b/jjb/publish.yaml
@@ -18,6 +18,10 @@
             echo "Error: ZUUL_UUID must be set, aborting."
             exit 1
          fi
+         if [ -z $DOC_SUBPATH ]; then
+            echo "Error: DOC_SUBPATH must be set, aborting."
+            exit 1
+         fi
          rsync --recursive "{docsrc}/" "rsync://10.68.16.255/doc/$ZUUL_UUID"
          echo
          echo "Publishing to https://doc.wikimedia.org/{docdest}/"
