Added per-browser tags to MobileFrontend builds
Paired with Chris McMahon.

Bug: 62846

diff --git a/job_template.yaml b/job_template.yaml
--- a/job_template.yaml
+++ b/job_template.yaml
@@ -110,6 +110,46 @@
           # run tests
           bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @{mediawiki_url} || (echo -e "\nJob has failed (exit code: $?)."; false)
 
+# MobileFrontend
+
+- job-template:
+    name: 'MobileFrontend-{name}'
+
+    builders:
+      - MobileFrontend:
+          browser: '{browser}'
+          folder: '{folder}'
+          mediawiki_password_variable: '{mediawiki_password_variable}'
+          mediawiki_url: '{mediawiki_url}'
+          mediawiki_user: '{mediawiki_user}'
+          platform: '{platform}'
+          version: '{version}'
+
+- builder:
+    name: MobileFrontend
+    builders:
+      - shell: |
+          # set up environment variables
+          export BROWSER={browser}
+          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
+          export MEDIAWIKI_URL=http://{mediawiki_url}/wiki/
+          export MEDIAWIKI_USER={mediawiki_user}
+          export PLATFORM='{platform}'
+          export VERSION={version}
+
+          # install ruby
+          curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
+          RUBY_VERSION=2.1.1 \
+            source ./use-ruby
+
+          # install ruby dependencies
+          gem install bundler --no-ri --no-rdoc
+          cd {folder}/browser/
+          bundle install
+
+          # run tests
+          bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @{mediawiki_url} --tags @{browser} || (echo -e "\nJob has failed (exit code: $?)."; false)
+
 # UniversalLanguageSelector
 
 - job-template:
