Refactored shell builders
Added comments, sorted variables alphabetically.

diff --git a/job_template.yaml b/job_template.yaml
--- a/job_template.yaml
+++ b/job_template.yaml
@@ -49,21 +49,25 @@
     name: default
     builders:
       - shell: |
-          export MEDIAWIKI_USER={mediawiki_user}
-          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
-
+          # set up environment variables
           export BROWSER={browser}
+          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
+          export MEDIAWIKI_URL=http://{mediawiki_url}/wiki/
+          export MEDIAWIKI_USER={mediawiki_user}
           export PLATFORM='{platform}'
           export VERSION={version}
-          export MEDIAWIKI_URL=http://{mediawiki_url}/wiki/
 
+          # install ruby
           curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
           RUBY_VERSION=2.1.1 \
             source ./use-ruby
 
+          # install ruby dependencies
           gem install bundler --no-ri --no-rdoc
           cd {folder}/browser/
           bundle install
+
+          # run tests
           bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @{mediawiki_url} || (echo -e "\nJob has failed (exit code: $?)."; false)
 
 # ContentTranslation
@@ -85,21 +89,25 @@
     name: ContentTranslation
     builders:
       - shell: |
-          export MEDIAWIKI_USER={mediawiki_user}
-          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
-
+          # set up environment variables
           export BROWSER={browser}
+          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
+          export MEDIAWIKI_URL=http://{mediawiki_url}/index.php/
+          export MEDIAWIKI_USER={mediawiki_user}
           export PLATFORM='{platform}'
           export VERSION={version}
-          export MEDIAWIKI_URL=http://{mediawiki_url}/index.php/
 
+          # install ruby
           curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
           RUBY_VERSION=2.1.1 \
             source ./use-ruby
 
+          # install ruby dependencies
           gem install bundler --no-ri --no-rdoc
           cd {folder}/browser/
           bundle install
+
+          # run tests
           bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @{mediawiki_url} || (echo -e "\nJob has failed (exit code: $?)."; false)
 
 # UniversalLanguageSelector
@@ -121,21 +129,25 @@
     name: UniversalLanguageSelector
     builders:
       - shell: |
-          export MEDIAWIKI_USER={mediawiki_user}
-          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
-
+          # set up environment variables
           export BROWSER={browser}
+          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
+          export MEDIAWIKI_URL=http://{mediawiki_url}/MediaWiki/core/index.php/
+          export MEDIAWIKI_USER={mediawiki_user}
           export PLATFORM='{platform}'
           export VERSION={version}
-          export MEDIAWIKI_URL=http://{mediawiki_url}/MediaWiki/core/index.php/
 
+          # install ruby
           curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
           RUBY_VERSION=2.1.1 \
             source ./use-ruby
 
+          # install ruby dependencies
           gem install bundler --no-ri --no-rdoc
           cd {folder}/browser/
           bundle install
+
+          # run tests
           bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @{mediawiki_url} || (echo -e "\nJob has failed (exit code: $?)."; false)
 
 # UploadWizard
@@ -173,27 +185,21 @@
     name: UploadWizard-api
     builders:
       - shell: |
+          # set up environment variables
           set -e
           export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
+
+          # install python
           virtualenv --distribute DEV
+
+          # install python dependencies
           DEV/bin/pip install -rtests/api/requirements.txt
+
+          # run tests
           DEV/bin/python tests/api/upload-wizard_tests.py --username "{mediawiki_user}" --api_url "http://{mediawiki_url}/w/api.php"
           DEV/bin/python tests/api/upload-wizard_tests.py --gen_new_image --username "{mediawiki_user}" --api_url "http://{mediawiki_url}/w/api.php"
 
 # VisualEditor
-
-- builder:
-    name: VisualEditor
-    builders:
-      - shell: |
-          export BROWSER={browser}
-          export PLATFORM='{platform}'
-          export VERSION={version}
-
-          gem install bundler --no-ri --no-rdoc
-          cd {folder}/browser/
-          bundle install
-          bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit features/verify_production_wikis.feature || (echo -e "\nJob has failed (exit code: $?)."; false)
 
 - job-template:
     name: 'VisualEditor-{name}'
@@ -207,6 +213,28 @@
           folder: '{folder}'
           platform: '{platform}'
           version: '{version}'
+
+- builder:
+    name: VisualEditor
+    builders:
+      - shell: |
+          # set up environment variables
+          export BROWSER={browser}
+          export PLATFORM='{platform}'
+          export VERSION={version}
+
+          # install ruby
+          curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
+          RUBY_VERSION=2.1.1 \
+            source ./use-ruby
+
+          # install ruby dependencies
+          gem install bundler --no-ri --no-rdoc
+          cd {folder}/browser/
+          bundle install
+
+          # run tests
+          bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit features/verify_production_wikis.feature || (echo -e "\nJob has failed (exit code: $?)."; false)
 
 # ZeroRatedMobileAccess
 
@@ -274,19 +302,23 @@
     name: browsertests
     builders:
       - shell: |
-          export MEDIAWIKI_USER={mediawiki_user}
-          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
-
+          # set up environment variables
           export BROWSER={browser}
+          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
+          export MEDIAWIKI_URL=http://{mediawiki_url}/wiki/
+          export MEDIAWIKI_USER={mediawiki_user}
           export PLATFORM='{platform}'
           export VERSION={version}
-          export MEDIAWIKI_URL=http://{mediawiki_url}/wiki/
 
+          # install ruby
           curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
           RUBY_VERSION=2.1.1 \
             source ./use-ruby
 
+          # install ruby dependencies
           gem install bundler --no-ri --no-rdoc
           cd {folder}/browser/
           bundle install
+
+          # run tests
           bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @{mediawiki_url} {additional_tags} || (echo -e "\nJob has failed (exit code: $?)."; false)
