perlint job and jobs for timeline extension
The '{name}-perlint' will run a basic linter on any .pl or .pm file. The
macro will lint all the scripts and fail afterward.

Had to make the wikibugs perlint a specific job since its script is
lacking the .pl file extension.

bug: 46263
Change-Id: I6eca8079c05e137baf9e56cd0c6234c1cc11b316

diff --git a/macro.yaml b/macro.yaml
--- a/macro.yaml
+++ b/macro.yaml
@@ -277,6 +277,23 @@
             pattern: '**/pep8.txt'
 
 - builder:
+      name: perllint
+      builders:
+       - shell: |
+          # File used to track down whether a perl file is failing syntax check
+          rm -f PHPLINT_FAILED
+
+          find . \
+            \( -name '*.pm' -or -name '*.pl' \) \
+            \( -exec perl -Mstrict -Mdiagnostics -cw {} \; \
+            -or -exec touch PHPLINT_FAILED  \; \)
+
+          # Set exit code to fail the build
+          if [ -e PHPLINT_FAILED ]; then
+              exit 1
+          fi;
+
+- builder:
     name: pyflakes
     builders:
      - shell: "pyflakes"
