Grep for jsduck warnings and exit nonzero for them
Change-Id: Ic01c83ffec3c135c44f1a3df40314f6935c72507

diff --git a/macro.yaml b/macro.yaml
--- a/macro.yaml
+++ b/macro.yaml
@@ -204,9 +204,19 @@
         else
             version="unknown"
         fi
-        jsduck --config="{config}" --footer="Generated for branch ${{version}} on {{DATE}} by {{JSDUCK}} {{VERSION}}." --color --warnings-exit-nonzero
+        set -o pipefail
+        jsduck --config="{config}" --footer="Generated for branch ${{version}} on {{DATE}} by {{JSDUCK}} {{VERSION}}." --warnings-exit-nonzero 2>&1 | tee jsduck.log
         ec=$?
-        # Exit with exit code of jsduck command
+        if [[ $ec -eq 0 ]]
+        then
+            grep "^Warning:" jsduck.log > /dev/null
+            gr=$?
+            if [[ $gr -eq 0 ]]
+            then
+                ec=1
+            fi
+        fi
+        # Exit with exit code of jsduck command, or whether we found errors
         exit $ec
 
 - builder:
