browsertests for some extensions
Should really use shell scripts instead.

cucumber is instructed to use the 'ciwmf' profile, letting author finely
tweak the settings.  We always skip tests tagged '@phantomjs-bug' though
since that is the browser we are using.

The MEDIAWIKI_URL needs 'index.php?title=' since there is no pathinfo
setup on the local wiki.

Creates jobs:

    mwext-browsertests-MobileFrontend-phantomjs
    mwext-browsertests-Translatewiki-phantomjs
    mwext-browsertests-UniversalLanguageSelector-phantomjs
    mwext-browsertests-VisualEditor-phantomjs

Change-Id: I4e7da6628395ab8eebb9cbd6a0a60d3f33759b18

diff --git a/mediawiki-extensions.yaml b/mediawiki-extensions.yaml
--- a/mediawiki-extensions.yaml
+++ b/mediawiki-extensions.yaml
@@ -10,6 +10,76 @@
     builders:
      - jshint
 
+# Template to run browsertests for an extension
+# Parameters: dependencies
+#
+- job-template:
+    name: '{name}-{ext-name}-phantomjs'
+    node: integration-selenium-driver # has the browsertest vhost
+    defaults: use-zuul-for-mw-ext
+    triggers:
+     - zuul
+
+    builders:
+     # setup mediawiki master + extension dependencies
+     - mw-setup-extension:
+        mwbranch: 'master'
+        dependencies: '{dependencies}'
+
+     - shell: |
+        # Let apache write in sqlite file
+        chmod a+w data/
+        chmod a+w data/*.sqlite
+
+     - shell: |
+        #!/bin/bash -x
+        TEST_ID=`echo "$ZUUL_PROJECT/$ZUUL_COMMIT/$BUILD_NUMBER" | tr '/' '-'`
+
+        # Post configure MediaWiki
+        echo "
+          <?php
+          # Injected by Jenkins
+          \$wgServer = 'http://localhost:9413/';
+          \$wgScriptPath = '/$TEST_ID';
+          \$wgScript = \$wgStylePath = \$wgLogo = false;
+          \$wgUsePathInfo = false;
+          " >> $WORKSPACE/LocalSettings.php
+
+        # On labs:
+        DOCROOT="/mnt/localhost-browsertests"
+
+        # Publish WORKSPACE in Apache
+        ln -s "$WORKSPACE" "$DOCROOT/$TEST_ID"
+        curl --location --include "http://localhost:9413/$TEST_ID/" |head -n42
+
+        cd extensions/{ext-name}/tests/browser
+            /srv/slave-scripts/tools/bundler/bundle install --path vendor
+            export BROWSER_LABEL="phantomjs"
+            export MEDIAWIKI_URL="http://localhost:9413/$TEST_ID/index.php?title="
+            export MEDIAWIKI_USER=WikiAdmin
+            export MEDIAWIKI_PASSWORD=testpass
+            /srv/slave-scripts/tools/bundler/bundle exec cucumber --color \
+                -p ciwmf \
+                -t ~@phantomjs-bug \
+                --format pretty \
+                --format junit --out "$WORKSPACE/junit" \
+                --format html --out "$WORKSPACE/report.html"
+        EXIT_CODE=$?
+        echo "Cucumber exit code: $EXIT_CODE"
+
+        # symlink cleanup
+        rm "$DOCROOT/$TEST_ID"
+
+        exit $EXIT_CODE
+
+    publishers:
+     - xunit:
+         types:
+          - junit:
+              pattern: 'junit/*.xml'
+     - archive:
+         artifacts: '*.log, report.html'
+
 - job-template:
     name: '{name}-{ext-name}-npmtest'
     node: hasNpm
@@ -538,6 +608,17 @@
 
      - 'mwext-VisualEditor-doc-publish':
         ext-name: VisualEditor
+
+- project:
+    name: mwext-browsertests
+    dependencies: ''
+    ext-name:
+     - MobileFrontend
+     - Translatewiki
+     - UniversalLanguageSelector
+     - VisualEditor
+    jobs:
+     - '{name}-{ext-name}-phantomjs'
 
 - project:
     name: 'mwext-BlameMaps'
