Created one VisualEditor job template to rule them all

diff --git a/VisualEditor.yaml b/VisualEditor.yaml
--- a/VisualEditor.yaml
+++ b/VisualEditor.yaml
@@ -2,6 +2,8 @@
     name: 'VisualEditor-{name}'
     browser: '{browser}'
     version: '{version}'
+    mediawiki_password_variable: '{mediawiki_password_variable}'
+    mediawiki_url: '{mediawiki_url}'
 
     disabled: false
 
@@ -18,12 +20,12 @@
       - shell: |
 
           export MEDIAWIKI_USER=Selenium_user
-          export MEDIAWIKI_PASSWORD_VARIABLE=MEDIAWIKI_PASSWORD_SELENIUM_USER_WMFLABS_ORG
+          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
 
           export BROWSER={browser}
           export PLATFORM=Linux
           export VERSION={version}
-          export MEDIAWIKI_URL=http://en.wikipedia.beta.wmflabs.org/wiki/
+          export MEDIAWIKI_URL=http://{mediawiki_url}/wiki/
 
           curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
           RUBY_VERSION=2.1.0 \
@@ -32,7 +34,7 @@
           gem install bundler --no-ri --no-rdoc
           cd modules/ve-mw/test/browser/
           bundle install
-          bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @en.wikipedia.beta.wmflabs.org || (echo -e "\nJob has failed (exit code: $?)."; false)
+          bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @{mediawiki_url} || (echo -e "\nJob has failed (exit code: $?)."; false)
 
     publishers:
       - junit:
@@ -53,6 +55,8 @@
     name: en.wikipedia.beta.wmflabs.org-linux-chrome
     browser: chrome
     version: 32
+    mediawiki_password_variable: MEDIAWIKI_PASSWORD_SELENIUM_USER_WMFLABS_ORG
+    mediawiki_url: en.wikipedia.beta.wmflabs.org
 
     jobs:
       - 'VisualEditor-{name}'
@@ -61,6 +65,28 @@
     name: en.wikipedia.beta.wmflabs.org-linux-firefox
     browser: firefox
     version: 27
+    mediawiki_password_variable: MEDIAWIKI_PASSWORD_SELENIUM_USER_WMFLABS_ORG
+    mediawiki_url: en.wikipedia.beta.wmflabs.org
+
+    jobs:
+      - 'VisualEditor-{name}'
+
+- project:
+    name: test2.wikipedia.org-linux-chrome
+    browser: chrome
+    version: 32
+    mediawiki_password_variable: MEDIAWIKI_PASSWORD_SELENIUM_USER_WIKIPEDIA_ORG
+    mediawiki_url: test2.wikipedia.org
+
+    jobs:
+      - 'VisualEditor-{name}'
+
+- project:
+    name: test2.wikipedia.org-linux-firefox
+    browser: firefox
+    version: 27
+    mediawiki_password_variable: MEDIAWIKI_PASSWORD_SELENIUM_USER_WIKIPEDIA_ORG
+    mediawiki_url: test2.wikipedia.org
 
     jobs:
       - 'VisualEditor-{name}'
