VisualEditor and WikiLove are using the same job template

diff --git a/WikiLove-en.wikipedia.beta.wmflabs.org-linux-firefox.yaml b/WikiLove-en.wikipedia.beta.wmflabs.org-linux-firefox.yaml
--- a/WikiLove-en.wikipedia.beta.wmflabs.org-linux-firefox.yaml
+++ b/WikiLove-en.wikipedia.beta.wmflabs.org-linux-firefox.yaml
@@ -1,10 +1,18 @@
-- job:
-    name: WikiLove-en.wikipedia.beta.wmflabs.org-linux-firefox
+- job-template:
+    name: 'WikiLove-{name}'
+    repository: '{repository}'
+    browser: '{browser}'
+    version: '{version}'
+    mediawiki_password_variable: '{mediawiki_password_variable}'
+    mediawiki_url: '{mediawiki_url}'
+    folder: '{folder}'
+    recipients: '{recipients}'
+
     disabled: false
 
     scm:
       - git:
-          url: https://gerrit.wikimedia.org/r/mediawiki/extensions/WikiLove
+          url: https://gerrit.wikimedia.org/r/mediawiki/extensions/{repository}
           branches:
             - master
 
@@ -13,30 +21,28 @@
 
     builders:
       - shell: |
-          git fetch https://gerrit.wikimedia.org/r/mediawiki/extensions/WikiLove refs/changes/04/113104/5 && git checkout FETCH_HEAD
-
           export MEDIAWIKI_USER=Selenium_user
-          export MEDIAWIKI_PASSWORD_VARIABLE=MEDIAWIKI_PASSWORD_SELENIUM_USER_WMFLABS_ORG
+          export MEDIAWIKI_PASSWORD_VARIABLE={mediawiki_password_variable}
 
-          export BROWSER=firefox
+          export BROWSER={browser}
           export PLATFORM=Linux
-          export VERSION=27
-          export MEDIAWIKI_URL=http://en.wikipedia.beta.wmflabs.org/wiki/
+          export VERSION={version}
+          export MEDIAWIKI_URL=http://{mediawiki_url}/wiki/
 
           curl -s -o use-ruby https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/ruby/use-ruby
           RUBY_VERSION=2.1.0 \
             source ./use-ruby
 
           gem install bundler --no-ri --no-rdoc
-          cd tests/browser/
+          cd {folder}/browser/
           bundle install
-          bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @en.wikipedia.beta.wmflabs.org || (echo -e "\nJob has failed (exit code: $?)."; false)
+          bundle exec cucumber --backtrace --verbose --format pretty --format Cucumber::Formatter::Sauce --out reports/junit --tags @{mediawiki_url} || (echo -e "\nJob has failed (exit code: $?)."; false)
 
     publishers:
       - junit:
-          results: tests/browser/reports/junit/*.xml
+          results: '{folder}/browser/reports/junit/*.xml'
       - email:
-          recipients: cmcmahon@wikimedia.org zfilipin@wikimedia.org
+          recipients: '{recipients}'
       - ircbot:
           strategy: all
           notify-start: false
@@ -46,3 +52,16 @@
           notify-fixers: false
           message-type: summary-scm
           matrix-notifier: only-configurations
+
+- project:
+    name: en.wikipedia.beta.wmflabs.org-linux-firefox
+    repository: WikiLove
+    browser: firefox
+    version: 27
+    mediawiki_password_variable: MEDIAWIKI_PASSWORD_SELENIUM_USER_WMFLABS_ORG
+    mediawiki_url: en.wikipedia.beta.wmflabs.org
+    folder: tests
+    recipients: cmcmahon@wikimedia.org zfilipin@wikimedia.org
+
+    jobs:
+      - 'WikiLove-{name}'
